# DEVELOPMENT
version: '3'

# Containers / Services
services:
  nginx:
    ports:
      - '3000:80'
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=garbalau
      - MONGO_PASSWORD=password
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=garbalau
      - MONGO_INITDB_ROOT_PASSWORD=password
